#!/usr/bin/env python3
"""
Plot the number of triple AGN systems as a function of redshift.
Analyzes catalogs generated by build_tripleagn_catalog.py across cosmic time.
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path
import glob
import re

# ============================================================================
# CONFIGURATION
# ============================================================================
CATALOG_DIR = "/scratch/stlock/tripleAGNs/catalogs/1e40lum/catalogue_30kpc/"
OUTPUT_DIR = "/scratch/stlock/tripleAGNs/plots_and_data/"
CATALOG_PATTERN = "TripleAGN-Catalog-R50-z*.pkl"

# ============================================================================
# LOAD DATA
# ============================================================================
def load_all_catalogs_with_redshift(catalog_dir, pattern):
    """
    Load all triple AGN catalogs and extract redshift information.
    Returns DataFrame with columns: redshift, n_systems, catalog_file
    """
    catalog_files = sorted(glob.glob(str(Path(catalog_dir) / pattern)))
    
    if len(catalog_files) == 0:
        raise FileNotFoundError(f"No catalog files found matching {pattern} in {catalog_dir}")
    
    print(f"Found {len(catalog_files)} catalog files")
    
    redshift_data = []
    
    for fpath in catalog_files:
        try:
            # Extract redshift from filename (e.g., "z0.50.pkl" -> 0.50)
            filename = Path(fpath).name
            z_match = re.search(r'z(\d+\.?\d*)', filename)
            
            if z_match:
                z = float(z_match.group(1))
            else:
                print(f"  Warning: Could not extract redshift from {filename}, skipping")
                continue
            
            # Load catalog
            df = pd.read_pickle(fpath)
            n_systems = len(df)
            
            redshift_data.append({
                'redshift': z,
                'n_systems': n_systems,
                'catalog_file': filename
            })
            
            print(f"  z={z:.2f}: {n_systems} systems")
            
        except Exception as e:
            print(f"  Error loading {fpath}: {e}")
    
    if len(redshift_data) == 0:
        raise ValueError("No valid data found in catalog files")
    
    # Convert to DataFrame and sort by redshift
    result_df = pd.DataFrame(redshift_data).sort_values('redshift').reset_index(drop=True)
    
    print(f"\nTotal catalogs loaded: {len(result_df)}")
    print(f"Redshift range: z={result_df['redshift'].min():.2f} to z={result_df['redshift'].max():.2f}")
    print(f"Total triple AGN systems: {result_df['n_systems'].sum()}")
    
    return result_df

# ============================================================================
# PLOTTING FUNCTIONS
# ============================================================================
def plot_n_systems_vs_redshift(df, output_dir):
    """
    Main plot: Number of triple AGN systems vs redshift.
    """
    fig, ax = plt.subplots(figsize=(12, 7))
    
    # Main line plot
    ax.plot(df['redshift'], df['n_systems'], 
            linewidth=2.5, color='steelblue', marker='o', 
            markersize=6, markerfacecolor='white', markeredgewidth=2,
            markeredgecolor='steelblue', label='Triple AGN systems')
    
    # Fill under the curve
    ax.fill_between(df['redshift'], 0, df['n_systems'], 
                    alpha=0.2, color='steelblue')
    
    # Styling
    ax.set_xlabel('Redshift (z)', fontsize=14, fontweight='bold')
    ax.set_ylabel('Number of Triple AGN Systems', fontsize=14, fontweight='bold')
    ax.set_title('Evolution of Triple AGN Systems with Cosmic Time', 
                fontsize=16, fontweight='bold', pad=20)
    
    # Grid
    ax.grid(True, alpha=0.3, linestyle='--', linewidth=0.8)
    ax.set_axisbelow(True)
    
    # Set x-axis limits
    ax.set_xlim(df['redshift'].min() - 0.1, df['redshift'].max() + 0.1)
    ax.set_ylim(0, df['n_systems'].max() * 1.1)
    
    # Add secondary x-axis with lookback time (approximate)
    def redshift_to_lookback_time(z):
        """Approximate lookback time in Gyr for a flat ΛCDM cosmology"""
        # Simplified formula: t ≈ 13.8 Gyr * (1 - 1/(1+z)^1.5)
        return 13.8 * (1 - 1/(1+z)**1.5)
    
    ax2 = ax.twiny()
    ax2.set_xlim(ax.get_xlim())
    
    # Create lookback time ticks at the same positions as redshift ticks
    z_ticks = ax.get_xticks()
    lookback_ticks = [redshift_to_lookback_time(z) if z >= 0 else 0 for z in z_ticks]
    
    ax2.set_xticks(z_ticks)
    ax2.set_xticklabels([f'{t:.1f}' for t in lookback_ticks])
    ax2.set_xlabel('Lookback Time (Gyr)', fontsize=12, fontweight='bold')
    
    # Add statistics text box
    total_systems = df['n_systems'].sum()
    max_systems = df['n_systems'].max()
    z_at_max = df.loc[df['n_systems'].idxmax(), 'redshift']
    
    stats_text = f'Total Systems: {total_systems}\n'
    stats_text += f'Peak: {max_systems} systems at z={z_at_max:.2f}\n'
    stats_text += f'Snapshots: {len(df)}'
    
    ax.text(0.02, 0.98, stats_text, transform=ax.transAxes,
            fontsize=11, verticalalignment='top',
            bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.8))
    
    plt.tight_layout()
    plt.savefig(Path(output_dir) / 'triple_agn_vs_redshift.png', dpi=300, bbox_inches='tight')
    print(f"Saved: triple_agn_vs_redshift.png")
    plt.close()

def plot_cumulative_systems(df, output_dir):
    """
    Plot cumulative number of triple AGN systems discovered.
    """
    fig, ax = plt.subplots(figsize=(12, 7))
    
    # Calculate cumulative sum (going backward in time, from high z to low z)
    df_sorted = df.sort_values('redshift', ascending=False).reset_index(drop=True)
    df_sorted['cumulative'] = df_sorted['n_systems'].cumsum()
    
    # Plot
    ax.plot(df_sorted['redshift'], df_sorted['cumulative'], 
            linewidth=2.5, color='darkgreen', marker='s', 
            markersize=6, markerfacecolor='white', markeredgewidth=2,
            markeredgecolor='darkgreen')
    
    ax.fill_between(df_sorted['redshift'], 0, df_sorted['cumulative'], 
                    alpha=0.2, color='darkgreen')
    
    # Styling
    ax.set_xlabel('Redshift (z)', fontsize=14, fontweight='bold')
    ax.set_ylabel('Cumulative Number of Systems', fontsize=14, fontweight='bold')
    ax.set_title('Cumulative Triple AGN Systems Since High Redshift', 
                fontsize=16, fontweight='bold', pad=20)
    
    ax.grid(True, alpha=0.3, linestyle='--', linewidth=0.8)
    ax.set_axisbelow(True)
    
    # Reverse x-axis so high redshift is on left (going forward in time)
    ax.invert_xaxis()
    
    ax.set_ylim(0, df_sorted['cumulative'].max() * 1.05)
    
    plt.tight_layout()
    plt.savefig(Path(output_dir) / 'cumulative_systems.png', dpi=300, bbox_inches='tight')
    print(f"Saved: cumulative_systems.png")
    plt.close()

def plot_systems_per_redshift_bin(df, output_dir, bin_width=0.5):
    """
    Plot number of systems in redshift bins (histogram style).
    """
    fig, ax = plt.subplots(figsize=(12, 7))
    
    # Create redshift bins
    z_min = 0
    z_max = 3
    bins = np.arange(z_min, z_max + bin_width, bin_width)
    bin_centers = bins[:-1] + bin_width/2
    
    # Count systems in each bin
    binned_counts = []
    for i in range(len(bins)-1):
        mask = (df['redshift'] >= bins[i]) & (df['redshift'] < bins[i+1])
        count = df.loc[mask, 'n_systems'].sum()
        binned_counts.append(count)
    
    # Bar plot
    ax.bar(bin_centers, binned_counts, width=bin_width*0.9, 
          color='coral', alpha=0.7, edgecolor='darkred', linewidth=1.5)
    
    # Styling
    ax.set_xlabel('Redshift (z)', fontsize=14, fontweight='bold')
    ax.set_ylabel('Number of Triple AGN Systems', fontsize=14, fontweight='bold')
    ax.set_title(f'Triple AGN Systems in Redshift Bins (Δz = {bin_width})', 
                fontsize=16, fontweight='bold', pad=20)
    
    ax.grid(True, alpha=0.3, linestyle='--', linewidth=0.8, axis='y')
    ax.set_axisbelow(True)
    
    ax.set_xlim(z_min - bin_width/2, z_max + bin_width/2)
    ax.set_ylim(0, max(binned_counts) * 1.1)
    
    # Add value labels on bars
    for center, count in zip(bin_centers, binned_counts):
        if count > 0:
            ax.text(center, count, str(count), 
                   ha='center', va='bottom', fontsize=9, fontweight='bold')
    
    plt.tight_layout()
    plt.savefig(Path(output_dir) / 'systems_per_redshift_bin.png', dpi=300, bbox_inches='tight')
    print(f"Saved: systems_per_redshift_bin.png")
    plt.close()

def plot_combined_overview(df, output_dir):
    """
    Multi-panel plot showing different perspectives.
    """
    fig, axes = plt.subplots(2, 2, figsize=(16, 12))
    
    # Panel 1: Main evolution plot
    ax = axes[0, 0]
    ax.plot(df['redshift'], df['n_systems'], 
            linewidth=2, color='steelblue', marker='o', markersize=5)
    ax.fill_between(df['redshift'], 0, df['n_systems'], alpha=0.2, color='steelblue')
    ax.set_xlabel('Redshift', fontsize=11, fontweight='bold')
    ax.set_ylabel('Number of Systems', fontsize=11, fontweight='bold')
    ax.set_title('Triple AGN Evolution', fontsize=12, fontweight='bold')
    ax.grid(True, alpha=0.3)
    
    # Panel 2: Log scale
    ax = axes[0, 1]
    # Only plot non-zero values for log scale
    df_nonzero = df[df['n_systems'] > 0]
    ax.semilogy(df_nonzero['redshift'], df_nonzero['n_systems'], 
                linewidth=2, color='darkred', marker='s', markersize=5)
    ax.set_xlabel('Redshift', fontsize=11, fontweight='bold')
    ax.set_ylabel('Number of Systems (log)', fontsize=11, fontweight='bold')
    ax.set_title('Triple AGN Evolution (Log Scale)', fontsize=12, fontweight='bold')
    ax.grid(True, alpha=0.3, which='both')
    
    # Panel 3: Rate of change
    ax = axes[1, 0]
    # Calculate derivative (rate of change)
    dz = df['redshift'].diff()
    dn = df['n_systems'].diff()
    rate = dn / dz
    
    ax.plot(df['redshift'].iloc[1:], rate.iloc[1:], 
            linewidth=2, color='green', marker='^', markersize=5)
    ax.axhline(y=0, color='black', linestyle='--', alpha=0.5)
    ax.set_xlabel('Redshift', fontsize=11, fontweight='bold')
    ax.set_ylabel('dN/dz (Rate of Change)', fontsize=11, fontweight='bold')
    ax.set_title('Rate of Change in Triple AGN Numbers', fontsize=12, fontweight='bold')
    ax.grid(True, alpha=0.3)
    
    # Panel 4: Statistics summary
    ax = axes[1, 1]
    ax.axis('off')
    
    # Calculate statistics
    total = df['n_systems'].sum()
    mean = df['n_systems'].mean()
    median = df['n_systems'].median()
    std = df['n_systems'].std()
    max_n = df['n_systems'].max()
    z_at_max = df.loc[df['n_systems'].idxmax(), 'redshift']
    
    # Count by redshift ranges
    z0_1 = df[(df['redshift'] >= 0) & (df['redshift'] < 1)]['n_systems'].sum()
    z1_2 = df[(df['redshift'] >= 1) & (df['redshift'] < 2)]['n_systems'].sum()
    z2_3 = df[(df['redshift'] >= 2) & (df['redshift'] <= 3)]['n_systems'].sum()
    
    summary = "═══ TRIPLE AGN STATISTICS ═══\n\n"
    summary += f"Total Systems: {total}\n"
    summary += f"Snapshots Analyzed: {len(df)}\n"
    summary += f"Redshift Range: {df['redshift'].min():.2f} - {df['redshift'].max():.2f}\n\n"
    
    summary += f"Mean per snapshot: {mean:.1f}\n"
    summary += f"Median per snapshot: {median:.1f}\n"
    summary += f"Std deviation: {std:.1f}\n\n"
    
    summary += f"Peak: {max_n} systems at z={z_at_max:.2f}\n\n"
    
    summary += "By Redshift Range:\n"
    summary += f"  0 ≤ z < 1:  {z0_1} ({100*z0_1/total:.1f}%)\n"
    summary += f"  1 ≤ z < 2:  {z1_2} ({100*z1_2/total:.1f}%)\n"
    summary += f"  2 ≤ z ≤ 3:  {z2_3} ({100*z2_3/total:.1f}%)\n"
    
    ax.text(0.5, 0.5, summary, transform=ax.transAxes,
            fontsize=12, verticalalignment='center', horizontalalignment='center',
            bbox=dict(boxstyle='round', facecolor='lightyellow', alpha=0.8),
            family='monospace')
    
    plt.tight_layout()
    plt.savefig(Path(output_dir) / 'combined_overview.png', dpi=300, bbox_inches='tight')
    print(f"Saved: combined_overview.png")
    plt.close()

# ============================================================================
# SUMMARY STATISTICS
# ============================================================================
def print_summary_statistics(df):
    """Print comprehensive summary statistics."""
    print("\n" + "="*70)
    print("TRIPLE AGN REDSHIFT EVOLUTION SUMMARY")
    print("="*70)
    
    print(f"\nTotal triple AGN systems: {df['n_systems'].sum()}")
    print(f"Snapshots analyzed: {len(df)}")
    print(f"Redshift range: z={df['redshift'].min():.2f} to z={df['redshift'].max():.2f}")
    
    print("\n--- Per-Snapshot Statistics ---")
    print(f"Mean systems per snapshot: {df['n_systems'].mean():.2f}")
    print(f"Median systems per snapshot: {df['n_systems'].median():.2f}")
    print(f"Std deviation: {df['n_systems'].std():.2f}")
    print(f"Min: {df['n_systems'].min()} systems")
    print(f"Max: {df['n_systems'].max()} systems")
    
    print("\n--- Peak Activity ---")
    max_idx = df['n_systems'].idxmax()
    print(f"Peak: {df.loc[max_idx, 'n_systems']} systems at z={df.loc[max_idx, 'redshift']:.2f}")
    
    print("\n--- Distribution by Redshift Range ---")
    z0_1 = df[(df['redshift'] >= 0) & (df['redshift'] < 1)]['n_systems'].sum()
    z1_2 = df[(df['redshift'] >= 1) & (df['redshift'] < 2)]['n_systems'].sum()
    z2_3 = df[(df['redshift'] >= 2) & (df['redshift'] <= 3)]['n_systems'].sum()
    total = df['n_systems'].sum()
    
    print(f"0 ≤ z < 1:  {z0_1:4d} systems ({100*z0_1/total:5.1f}%)")
    print(f"1 ≤ z < 2:  {z1_2:4d} systems ({100*z1_2/total:5.1f}%)")
    print(f"2 ≤ z ≤ 3:  {z2_3:4d} systems ({100*z2_3/total:5.1f}%)")
    
    print("\n--- Snapshots with Zero Systems ---")
    zero_snapshots = df[df['n_systems'] == 0]
    print(f"Number: {len(zero_snapshots)}")
    if len(zero_snapshots) > 0:
        print(f"Redshifts: {', '.join([f'{z:.2f}' for z in zero_snapshots['redshift'].values])}")
    
    print("="*70 + "\n")

# ============================================================================
# MAIN EXECUTION
# ============================================================================
def main():
    """Main analysis pipeline."""
    # Create output directory
    Path(OUTPUT_DIR).mkdir(parents=True, exist_ok=True)
    
    print("Loading triple AGN catalogs...")
    df = load_all_catalogs_with_redshift(CATALOG_DIR, CATALOG_PATTERN)
    
    print("\nGenerating plots...")
    plot_n_systems_vs_redshift(df, OUTPUT_DIR)
    plot_cumulative_systems(df, OUTPUT_DIR)
    plot_systems_per_redshift_bin(df, OUTPUT_DIR, bin_width=0.5)
    plot_combined_overview(df, OUTPUT_DIR)
    
    print_summary_statistics(df)
    
    # Save summary data
    summary_path = Path(OUTPUT_DIR) / 'triple_agn_vs_redshift.csv'
    df.to_csv(summary_path, index=False)
    print(f"\nSaved redshift data to: {summary_path}")
    
    print(f"\nAll plots saved to: {OUTPUT_DIR}")
    print("Analysis complete!")

if __name__ == "__main__":
    main()